.TH "DOTFLZ PASTE" "1" "11-Jan-2020" "" "dotflz paste Manual"
.SH NAME
dotflz\-paste \- Replace original files with ones from configured directory.
.SH SYNOPSIS
.B dotflz paste
[OPTIONS] CONFIG_PATH
.SH DESCRIPTION
Replace original files with ones from configured directory according to CONFIG_PATH config file.
