.TH "DOTFLZ RESTORE" "1" "11-Jan-2020" "" "dotflz restore Manual"
.SH NAME
dotflz\-restore \- Restore original files with specified backup directory.
.SH SYNOPSIS
.B dotflz restore
[OPTIONS] CONFIG_PATH BACKUP_DIR_NAME
.SH DESCRIPTION
Restore original files from BACKUP_DIR_NAME according to CONFIG_PATH config file.
