.TH "DOTFLZ COPY" "1" "11-Jan-2020" "" "dotflz copy Manual"
.SH NAME
dotflz\-copy \- Copy files by specified configuration file
.SH SYNOPSIS
.B dotflz copy
[OPTIONS] CONFIG_PATH
.SH DESCRIPTION
Copy files by according to CONFIG_PATH config file.
.SH OPTIONS
.TP
\fB\-c,\fP \-\-clean
Delete files missing from config file.
