.TH "DOTFLZ" "1" "11-Jan-2020" "" "dotflz Manual"
.SH NAME
dotflz \- Utility to keep copies of dotfiles in one...
.SH SYNOPSIS
.B dotflz
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Utility to keep copies of dotfiles in one place.
.SH COMMANDS
.PP
\fBcopy\fP
  Copy files by specified configuration file
  See \fBdotflz-copy(1)\fP for full documentation on the \fBcopy\fP command.
.PP
\fBpaste\fP
  Replace original files with ones from configured directory.
  See \fBdotflz-paste(1)\fP for full documentation on the \fBpaste\fP command.
.PP
\fBverify\fP
  Verify configuration file.
  See \fBdotflz-verify(1)\fP for full documentation on the \fBverify\fP command.
.PP
\fBbackup\fP
  Backup original files into backup directory.
  See \fBdotflz-backup(1)\fP for full documentation on the \fBbackup\fP command.
.PP
\fBrestore\fP
  Restore original files with specified backup directory.
  See \fBdotflz-restore(1)\fP for full documentation on the \fBrestore\fP command.
