language: python
install:
  - pip install .
  - pip install codecov
before_script:
  - chmod +x bin/dotflz
script:
  - bin/dotflz
  - python -m unittest
after_success:
  - coverage run --source dotflz setup.py test
  - codecov