#!/usr/bin/env python3

from parser import *


def _setup(config_path):
    click.echo(f'Config file: {config_path}')
    config = parse_config(config_path)
    click.echo('[\n' + '\n'.join('\t{}'.format(e) for _, e in enumerate(config.items)) + '\n]')
    return config


@click.group('dotflz')
def dotflz():
    pass


@dotflz.command(short_help='Copy files by specified configuration file')
@click.argument('config_path')
@click.option('-c', '--clean', is_flag=True, help='Delete files missing from config file.')
def copy(config_path, clean):
    """
    Copy files by specified configuration file located in CONFIG_PATH
    """
    config = _setup(config_path)
    if clean:
        config.clean()
    for item in config.items:
        item.copy()


@dotflz.command(short_help='Verify configuration file')
@click.argument('config_path')
def verify(config_path):
    """
    Verify configuration file located in CONFIG_PATH
    """
    config = _setup(config_path)
    are_files_valid = []
    for entry in config.items:
        are_files_valid.append(entry.is_valid())
    error_count = len(list(filter(lambda e: not e, are_files_valid)))
    click.echo(f'verification complete with {error_count} error{"" if error_count == 1 else "s"}')
    if error_count != 0:
        exit(1)


dotflz()
